version: '3.2'

services:
  client:
    image: tquinlan1992/webpack-react:docker
    build:
        context: ../
    volumes:
       - type: bind
         source: ../src
         target: /client-app/src
    ports:
      - "8000:8000"

volumes:
  data: {}
